import { WidgetDefinition, WidgetSection, WidgetSize, WidgetSizeConfig } from '@shared/types';

export const MOTIVATIONAL_QUOTES: string[] = [
  'Ogni esame superato è un passo in più verso il tuo futuro.',
  'La costanza batte il talento quando il talento non si impegna.',
  'Non studiare per il voto, studia per te stesso.',
  'Un giorno alla volta. Un esame alla volta.',
  'Il successo è la somma di piccoli sforzi ripetuti ogni giorno.',
  'Anche il percorso più lungo inizia con un singolo passo.',
  'Sii curioso, non ansioso.',
  'Le difficoltà di oggi sono le competenze di domani.',
  'Ogni nota sul libretto racconta la tua storia.',
  'Studia come se dovessi vivere per sempre, vivi come se dovessi morire domani.',
];

export const GRID_COLS = 3;
export const GRID_ROWS = 40;

export const WIDGET_SIZE_CONFIG: Record<WidgetSize, WidgetSizeConfig> = {
  small: { cols: 1, rows: 1, label: 'Piccolo', description: "Info essenziale, a colpo d'occhio" },
  medium: { cols: 2, rows: 2, label: 'Medio', description: 'Più contesto e dettagli utili' },
  large: { cols: 3, rows: 3, label: 'Grande', description: 'Vista completa con tutti i dati' },
};

export const WIDGET_SECTIONS: WidgetSection[] = [
  {
    id: 'career',
    label: 'Carriera',
    widgets: [
      {
        id: 'career-arithmetic-avg',
        label: 'Media Aritmetica',
        description: 'La tua media aritmetica aggiornata.',
        icon: 'chart-line',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'career',
        section: 'career',
      },
      {
        id: 'career-base',
        label: 'Base di Laurea',
        description: 'La tua base di laurea attuale.',
        icon: 'chart-line',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'career',
        section: 'career',
      },
      {
        id: 'career-cfu',
        label: 'CFU',
        description: 'I tuoi CFU accumulati sul totale.',
        icon: 'graduation-cap',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'career',
        section: 'career',
      },
      {
        id: 'career-overview',
        label: 'Carriera Panoramica',
        description: 'Panoramica completa della tua carriera accademica.',
        icon: 'chart-line',
        availableSizes: ['medium', 'large'],
        defaultSize: 'medium',
        color: 'career',
        section: 'career',
      },
      {
        id: 'career-weighted-avg',
        label: 'Media Ponderata',
        description: 'La tua media ponderata aggiornata.',
        icon: 'chart-line',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'career',
        section: 'career',
      },
    ],
  },
  {
    id: 'exams',
    label: 'Appelli',
    widgets: [
      {
        id: 'exams-upcoming',
        label: 'I Miei Prossimi Appelli',
        description: 'Gli appelli che hai prenotato.',
        icon: 'calendar-check',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'exams',
        section: 'exams',
      },
      {
        id: 'exams-available',
        label: 'Appelli Disponibili',
        description: 'Gli appelli che puoi ancora prenotare.',
        icon: 'calendar-days',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'exams',
        section: 'exams',
      },
    ],
  },
  {
    id: 'agenda',
    label: 'Agenda',
    widgets: [
      {
        id: 'agenda-today',
        label: 'Agenda Oggi',
        description: 'Gli eventi di oggi.',
        icon: 'calendar-days',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'agenda',
        section: 'agenda',
      },
      {
        id: 'agenda-monthly',
        label: 'Agenda Mensile',
        description: 'Il calendario mensile con tutti gli eventi.',
        icon: 'calendar-days',
        availableSizes: ['large'],
        defaultSize: 'large',
        color: 'agenda',
        section: 'agenda',
      },
    ],
  },
  {
    id: 'schedules',
    label: 'Orario Lezioni',
    widgets: [
      {
        id: 'schedules-overview',
        label: 'Orario Lezioni',
        description: 'Il tuo orario lezioni del corso di laurea.',
        icon: 'calendar-clock',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'schedules',
        section: 'schedules',
      },
    ],
  },
  {
    id: 'future',
    label: 'Sviluppi Futuri',
    widgets: [
      {
        id: 'future-placeholder',
        label: 'Sviluppi Futuri',
        description: 'Widget sviluppi futuri in arrivo.',
        icon: 'signpost-big',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'future',
        section: 'future',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'messages',
    label: 'Messaggi',
    widgets: [
      {
        id: 'messages-placeholder',
        label: 'Messaggi',
        description: 'Widget messaggi in arrivo.',
        icon: 'message-square',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'messages',
        section: 'messages',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'transport',
    label: 'Trasporti',
    widgets: [
      {
        id: 'transport-placeholder',
        label: 'Trasporti',
        description: 'Widget trasporti in arrivo.',
        icon: 'bus',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'transport',
        section: 'transport',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'classrooms',
    label: 'Aule',
    widgets: [
      {
        id: 'classrooms-placeholder',
        label: 'Aule',
        description: 'Widget aule in arrivo.',
        icon: 'door-open',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'classrooms',
        section: 'classrooms',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'portals',
    label: 'Portali',
    widgets: [
      {
        id: 'portals-esse3',
        label: 'Esse3 / Cineca',
        description: 'Accesso rapido al portale Esse3.',
        icon: 'external-link',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'portals',
        section: 'portals',
      },
      {
        id: 'portals-mail',
        label: 'Mail Universitaria',
        description: 'Accesso rapido alla mail universitaria.',
        icon: 'external-link',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'portals',
        section: 'portals',
      },
      {
        id: 'portals-moodle',
        label: 'Moodle',
        description: 'Accesso rapido al portale Moodle.',
        icon: 'external-link',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'portals',
        section: 'portals',
      },
      {
        id: 'portals-overview',
        label: 'Portali Panoramica',
        description: "Tutti i portali universitari in un colpo d'occhio.",
        icon: 'external-link',
        availableSizes: ['medium', 'large'],
        defaultSize: 'medium',
        color: 'portals',
        section: 'portals',
      },
      {
        id: 'portals-website',
        label: 'Sito Web',
        description: "Accesso rapido al sito web dell'ateneo.",
        icon: 'external-link',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'portals',
        section: 'portals',
      },
    ],
  },
  {
    id: 'partner',
    label: 'Partner',
    widgets: [
      {
        id: 'partner-placeholder',
        label: 'Partner',
        description: 'Widget partner in arrivo.',
        icon: 'handshake',
        availableSizes: ['small'],
        defaultSize: 'small',
        color: 'partner',
        section: 'partner',
        comingSoon: true,
      },
    ],
  },
  {
    id: 'contacts',
    label: 'Contatti Universitari',
    widgets: [
      {
        id: 'contacts-teachers',
        label: 'Contatti Docenti',
        description: 'Rubrica completa dei docenti.',
        icon: 'contact-round',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'contacts',
        section: 'contacts',
      },
      {
        id: 'contacts-useful',
        label: 'Numeri Utili',
        description: "Rubrica dei numeri utili dell'ateneo.",
        icon: 'contact-round',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'contacts',
        section: 'contacts',
      },
    ],
  },
  {
    id: 'secretariat',
    label: 'Segreteria',
    widgets: [
      {
        id: 'secretariat-calls',
        label: 'Bandi e Concorsi',
        description: 'Elenco dei bandi e concorsi attivi.',
        icon: 'printer',
        availableSizes: ['large'],
        defaultSize: 'large',
        color: 'secretariat',
        section: 'secretariat',
      },
      {
        id: 'secretariat-grants',
        label: 'Borse di Studio',
        description: 'Elenco delle borse di studio disponibili.',
        icon: 'printer',
        availableSizes: ['large'],
        defaultSize: 'large',
        color: 'secretariat',
        section: 'secretariat',
      },
      {
        id: 'secretariat-forms',
        label: 'Modulistica',
        description: 'Elenco della modulistica disponibile.',
        icon: 'printer',
        availableSizes: ['large'],
        defaultSize: 'large',
        color: 'secretariat',
        section: 'secretariat',
      },
      {
        id: 'secretariat-overview',
        label: 'Segreteria Panoramica',
        description: 'Ultima risorsa pubblicata dalla segreteria.',
        icon: 'printer',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'secretariat',
        section: 'secretariat',
      },
      {
        id: 'secretariat-taxes',
        label: 'Tasse',
        description: 'Gestione e info sulle tasse universitarie.',
        icon: 'printer',
        availableSizes: ['medium'],
        defaultSize: 'medium',
        color: 'secretariat',
        section: 'secretariat',
      },
    ],
  },
];

export const AVAILABLE_WIDGETS: WidgetDefinition[] = WIDGET_SECTIONS.flatMap(s => s.widgets);

export const WIDGET_COL_SPAN_CLASS: Record<WidgetSize, string> = {
  small: 'col-span-1',
  medium: 'col-span-2',
  large: 'col-span-3',
};
